@startuml
'https://plantuml.com/sequence-diagram

class Solution42{
+main()
}
class FileParser{
-List<String> data
-List<Map<String, String>> mappedData
+getData()
+getMappedData()
+readData()
-getNextCommaPos()
+mapData()
}
class ParsedDataPrinter{
-getLongestStringLength()
+printTabularData()
}

Solution42 -- ParsedDataPrinter
FileParser <|-- ParsedDataPrinter
@enduml