@startuml
'https://plantuml.com/sequence-diagram

class Solution43{
+main()
}
class SiteMaker{
+getPromptedUserInput()
-generateFolder()
-generateHTML()
+generateSite()
}
Solution43 -- SiteMaker
@enduml